#!/usr/bin/env python3
"""Emit the colored character SVGs from the shared spec.

``whisper_face_characters`` owns the geometry; this script replays it into
``icons/faces/color`` so AppKit surfaces that cannot run the HUD's Core
Graphics path still show the real character instead of a menu-bar glyph
scaled past the size it was drawn for.

The flat template silhouettes in ``icons/faces`` are hand-authored artwork for
the 18-point menu bar and are deliberately left alone.

Run after any change to ``whisper_face_characters.py``:

    uv run scripts/generate_face_art.py

``--check`` re-renders into memory and fails if the committed files have
drifted, which is what the installer parity test uses.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from whisper_face_characters import (  # noqa: E402
    DESIGN_SIZE,
    FACE_ORDER,
    character_body,
    character_svg,
)

OUTPUT_DIR = ROOT / "icons" / "faces" / "color"
SITE_ART = ROOT / "site" / "src" / "data" / "face-art.ts"
BANNER = "<!-- Generated by scripts/generate_face_art.py. Do not edit. -->\n"


def _site_module() -> str:
    """The site's copy of the art, generated rather than hand-duplicated.

    The colored characters use no <mask> elements, so unlike the flat
    silhouettes they carry no element ids and many can share one page without
    colliding.
    """
    lines = [
        "// Generated by scripts/generate_face_art.py. Do not edit.",
        "// Source of truth: whisper_face_characters.py",
        "//",
        "// The colored character for each face, as inline SVG bodies. The flat",
        "// silhouettes in faces.ts stay hand-authored: they are the menu-bar",
        "// template artwork and are drawn to survive 18 points. `half` is the",
        "// mid-syllable frame the flap animation passes through.",
        "import type { Animal } from './faces';",
        "",
        "export const FACE_ART: Record<"
        "Animal, { idle: string; half: string; talk: string }> = {",
    ]
    for face in FACE_ORDER:
        lines.append(f"  {face}: {{")
        for state in ("idle", "half", "talk"):
            body = character_body(face, frame=state, whispers=False)
            lines.append(f"    {state}: `{body}`,")
        lines.append("  },")
    lines += [
        "};",
        "",
        f"export const FACE_VIEWBOX = '0 0 {DESIGN_SIZE:g} {DESIGN_SIZE:g}';",
        "",
    ]
    return "\n".join(lines)


def rendered_files() -> dict[Path, str]:
    """Map every generated path to the exact bytes it should contain."""
    files: dict[Path, str] = {}
    for face in FACE_ORDER:
        for state in ("idle", "half", "talk"):
            # The app window shows the character inside a tight chip, where
            # the trailing speech puffs would clip against the chip edge.
            body = character_svg(face, frame=state, whispers=False)
            files[OUTPUT_DIR / f"{face}-{state}.svg"] = BANNER + body + "\n"
    files[SITE_ART] = _site_module()
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="fail if the committed art differs from the spec")
    args = parser.parse_args()

    files = rendered_files()
    if args.check:
        drifted = [
            path for path, content in files.items()
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        if drifted:
            for path in sorted(drifted):
                print(f"stale: {path.relative_to(ROOT)}", file=sys.stderr)
            print("run: uv run scripts/generate_face_art.py", file=sys.stderr)
            return 1
        print(f"{len(files)} generated face assets match the spec")
        return 0

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in sorted(files.items()):
        path.write_text(content, encoding="utf-8")
    print(f"wrote {len(files)} face assets to "
          f"{OUTPUT_DIR.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
